INSERT INTO place_autocomplete_entry (
    source_type, source_ref, entry_type, display_text, normalized_text,
    primary_text, secondary_text, latitude, longitude, search_weight, enabled, updated_at
) VALUES
('KOREA_SEED', 'city:서울특별시', 'CITY', '서울특별시', '서울특별시', '서울특별시', '서울특별시', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:부산광역시', 'CITY', '부산광역시', '부산광역시', '부산광역시', '부산광역시', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:대구광역시', 'CITY', '대구광역시', '대구광역시', '대구광역시', '대구광역시', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:인천광역시', 'CITY', '인천광역시', '인천광역시', '인천광역시', '인천광역시', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:광주광역시', 'CITY', '광주광역시', '광주광역시', '광주광역시', '광주광역시', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:대전광역시', 'CITY', '대전광역시', '대전광역시', '대전광역시', '대전광역시', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:울산광역시', 'CITY', '울산광역시', '울산광역시', '울산광역시', '울산광역시', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:세종특별자치시', 'CITY', '세종특별자치시', '세종특별자치시', '세종특별자치시', '세종특별자치시', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:경기도', 'CITY', '경기도', '경기도', '경기도', '경기도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:강원특별자치도', 'CITY', '강원특별자치도', '강원특별자치도', '강원특별자치도', '강원특별자치도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:충청북도', 'CITY', '충청북도', '충청북도', '충청북도', '충청북도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:충청남도', 'CITY', '충청남도', '충청남도', '충청남도', '충청남도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:전북특별자치도', 'CITY', '전북특별자치도', '전북특별자치도', '전북특별자치도', '전북특별자치도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:전라남도', 'CITY', '전라남도', '전라남도', '전라남도', '전라남도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:경상북도', 'CITY', '경상북도', '경상북도', '경상북도', '경상북도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:경상남도', 'CITY', '경상남도', '경상남도', '경상남도', '경상남도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'city:제주특별자치도', 'CITY', '제주특별자치도', '제주특별자치도', '제주특별자치도', '제주특별자치도', NULL, NULL, 400, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:종로구', 'DISTRICT', '종로구', '종로구', '종로구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:중구', 'DISTRICT', '중구', '중구', '중구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:용산구', 'DISTRICT', '용산구', '용산구', '용산구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:성동구', 'DISTRICT', '성동구', '성동구', '성동구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:광진구', 'DISTRICT', '광진구', '광진구', '광진구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:동대문구', 'DISTRICT', '동대문구', '동대문구', '동대문구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:중랑구', 'DISTRICT', '중랑구', '중랑구', '중랑구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:성북구', 'DISTRICT', '성북구', '성북구', '성북구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:강북구', 'DISTRICT', '강북구', '강북구', '강북구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:도봉구', 'DISTRICT', '도봉구', '도봉구', '도봉구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:노원구', 'DISTRICT', '노원구', '노원구', '노원구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:은평구', 'DISTRICT', '은평구', '은평구', '은평구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:서대문구', 'DISTRICT', '서대문구', '서대문구', '서대문구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:마포구', 'DISTRICT', '마포구', '마포구', '마포구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:양천구', 'DISTRICT', '양천구', '양천구', '양천구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:강서구', 'DISTRICT', '강서구', '강서구', '강서구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:구로구', 'DISTRICT', '구로구', '구로구', '구로구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:금천구', 'DISTRICT', '금천구', '금천구', '금천구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:영등포구', 'DISTRICT', '영등포구', '영등포구', '영등포구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:동작구', 'DISTRICT', '동작구', '동작구', '동작구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:관악구', 'DISTRICT', '관악구', '관악구', '관악구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:서초구', 'DISTRICT', '서초구', '서초구', '서초구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:강남구', 'DISTRICT', '강남구', '강남구', '강남구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:송파구', 'DISTRICT', '송파구', '송파구', '송파구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'district:서울특별시:강동구', 'DISTRICT', '강동구', '강동구', '강동구', '서울특별시', NULL, NULL, 320, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:부산광역시:서면', 'NEIGHBORHOOD', '서면', '서면', '서면', '부산광역시 부산진구', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:부산광역시:남포동', 'NEIGHBORHOOD', '남포동', '남포동', '남포동', '부산광역시 중구', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:부산광역시:광복동', 'NEIGHBORHOOD', '광복동', '광복동', '광복동', '부산광역시 중구', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:부산광역시:해운대', 'LANDMARK', '해운대', '해운대', '해운대', '부산광역시 해운대구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:부산광역시:광안리', 'LANDMARK', '광안리', '광안리', '광안리', '부산광역시 수영구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:부산광역시:해운대해수욕장', 'LANDMARK', '해운대해수욕장', '해운대해수욕장', '해운대해수욕장', '부산광역시 해운대구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:대구광역시:동성로', 'LANDMARK', '동성로', '동성로', '동성로', '대구광역시 중구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:대구광역시:동대구역', 'LANDMARK', '동대구역', '동대구역', '동대구역', '대구광역시 동구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:인천광역시:송도동', 'NEIGHBORHOOD', '송도동', '송도동', '송도동', '인천광역시 연수구', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:인천광역시:청라동', 'NEIGHBORHOOD', '청라동', '청라동', '청라동', '인천광역시 서구', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:인천광역시:인천공항', 'LANDMARK', '인천공항', '인천공항', '인천공항', '인천광역시 중구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:광주광역시:충장로', 'LANDMARK', '충장로', '충장로', '충장로', '광주광역시 동구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:대전광역시:둔산동', 'NEIGHBORHOOD', '둔산동', '둔산동', '둔산동', '대전광역시 서구', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:대전광역시:대전역', 'LANDMARK', '대전역', '대전역', '대전역', '대전광역시 동구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:울산광역시:삼산동', 'NEIGHBORHOOD', '삼산동', '삼산동', '삼산동', '울산광역시 남구', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:울산광역시:태화강', 'LANDMARK', '태화강', '태화강', '태화강', '울산광역시 중구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:경기도:판교', 'LANDMARK', '판교', '판교', '판교', '경기도 성남시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:경기도:수원역', 'LANDMARK', '수원역', '수원역', '수원역', '경기도 수원시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:경기도:일산', 'LANDMARK', '일산', '일산', '일산', '경기도 고양시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:경기도:동탄', 'LANDMARK', '동탄', '동탄', '동탄', '경기도 화성시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:강원특별자치도:주문진읍', 'TOWN', '주문진읍', '주문진읍', '주문진읍', '강원특별자치도 강릉시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:충청북도:오창읍', 'TOWN', '오창읍', '오창읍', '오창읍', '충청북도 청주시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:충청북도:오송읍', 'TOWN', '오송읍', '오송읍', '오송읍', '충청북도 청주시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:충청남도:천안아산역', 'LANDMARK', '천안아산역', '천안아산역', '천안아산역', '충청남도 천안시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:전북특별자치도:전주', 'LANDMARK', '전주', '전주', '전주', '전북특별자치도 전주시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:전라남도:여수', 'LANDMARK', '여수', '여수', '여수', '전라남도 여수시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:경상북도:경주', 'LANDMARK', '경주', '경주', '경주', '경상북도 경주시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:경상남도:창원', 'LANDMARK', '창원', '창원', '창원', '경상남도 창원시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:제주특별자치도:조천읍', 'TOWN', '조천읍', '조천읍', '조천읍', '제주특별자치도 제주시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:제주특별자치도:애월읍', 'TOWN', '애월읍', '애월읍', '애월읍', '제주특별자치도 제주시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:제주특별자치도:한림읍', 'TOWN', '한림읍', '한림읍', '한림읍', '제주특별자치도 제주시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:제주특별자치도:구좌읍', 'TOWN', '구좌읍', '구좌읍', '구좌읍', '제주특별자치도 제주시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:제주특별자치도:한경면', 'TOWN', '한경면', '한경면', '한경면', '제주특별자치도 제주시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'local:제주특별자치도:성산읍', 'TOWN', '성산읍', '성산읍', '성산읍', '제주특별자치도 서귀포시', NULL, NULL, 230, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:관악산', 'LANDMARK', '관악산', '관악산', '관악산', '서울특별시 관악구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:북한산', 'LANDMARK', '북한산', '북한산', '북한산', '서울특별시 은평구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:남산', 'LANDMARK', '남산', '남산', '남산', '서울특별시 중구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:한라산', 'LANDMARK', '한라산', '한라산', '한라산', '제주특별자치도', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:해운대', 'LANDMARK', '해운대', '해운대', '해운대', '부산광역시 해운대구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:광안리', 'LANDMARK', '광안리', '광안리', '광안리', '부산광역시 수영구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:해운대해수욕장', 'LANDMARK', '해운대해수욕장', '해운대해수욕장', '해운대해수욕장', '부산광역시 해운대구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:광안리해수욕장', 'LANDMARK', '광안리해수욕장', '광안리해수욕장', '광안리해수욕장', '부산광역시 수영구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:설악산', 'LANDMARK', '설악산', '설악산', '설악산', '강원특별자치도', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:지리산', 'LANDMARK', '지리산', '지리산', '지리산', '전라남도/경상남도', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:팔공산', 'LANDMARK', '팔공산', '팔공산', '팔공산', '대구광역시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:무등산', 'LANDMARK', '무등산', '무등산', '무등산', '광주광역시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:한강', 'LANDMARK', '한강', '한강', '한강', '서울특별시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:에버랜드', 'LANDMARK', '에버랜드', '에버랜드', '에버랜드', '경기도 용인시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:롯데월드', 'LANDMARK', '롯데월드', '롯데월드', '롯데월드', '서울특별시 송파구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:코엑스', 'LANDMARK', '코엑스', '코엑스', '코엑스', '서울특별시 강남구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:서울역', 'LANDMARK', '서울역', '서울역', '서울역', '서울특별시 중구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:강남역', 'LANDMARK', '강남역', '강남역', '강남역', '서울특별시 강남구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:홍대입구', 'LANDMARK', '홍대입구', '홍대입구', '홍대입구', '서울특별시 마포구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:신촌', 'LANDMARK', '신촌', '신촌', '신촌', '서울특별시 서대문구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:부산역', 'LANDMARK', '부산역', '부산역', '부산역', '부산광역시 동구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:대전역', 'LANDMARK', '대전역', '대전역', '대전역', '대전광역시 동구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:광주송정역', 'LANDMARK', '광주송정역', '광주송정역', '광주송정역', '광주광역시 광산구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:김포공항', 'LANDMARK', '김포공항', '김포공항', '김포공항', '서울특별시 강서구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:인천공항', 'LANDMARK', '인천공항', '인천공항', '인천공항', '인천광역시 중구', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'landmark:제주공항', 'LANDMARK', '제주공항', '제주공항', '제주공항', '제주특별자치도 제주시', NULL, NULL, 260, TRUE, CURRENT_TIMESTAMP)
,('KOREA_SEED', 'subway:서울:시청역', 'SUBWAY_STATION', '시청역', '시청역', '시청역', '서울특별시 중구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:을지로입구역', 'SUBWAY_STATION', '을지로입구역', '을지로입구역', '을지로입구역', '서울특별시 중구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:종각역', 'SUBWAY_STATION', '종각역', '종각역', '종각역', '서울특별시 종로구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:종로3가역', 'SUBWAY_STATION', '종로3가역', '종로3가역', '종로3가역', '서울특별시 종로구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:안국역', 'SUBWAY_STATION', '안국역', '안국역', '안국역', '서울특별시 종로구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:경복궁역', 'SUBWAY_STATION', '경복궁역', '경복궁역', '경복궁역', '서울특별시 종로구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:광화문역', 'SUBWAY_STATION', '광화문역', '광화문역', '광화문역', '서울특별시 종로구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:충무로역', 'SUBWAY_STATION', '충무로역', '충무로역', '충무로역', '서울특별시 중구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:동대문역사문화공원역', 'SUBWAY_STATION', '동대문역사문화공원역', '동대문역사문화공원역', '동대문역사문화공원역', '서울특별시 중구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:서울역', 'SUBWAY_STATION', '서울역', '서울역', '서울역', '서울특별시 중구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:홍대입구역', 'SUBWAY_STATION', '홍대입구역', '홍대입구역', '홍대입구역', '서울특별시 마포구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:신촌역', 'SUBWAY_STATION', '신촌역', '신촌역', '신촌역', '서울특별시 서대문구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:합정역', 'SUBWAY_STATION', '합정역', '합정역', '합정역', '서울특별시 마포구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:여의도역', 'SUBWAY_STATION', '여의도역', '여의도역', '여의도역', '서울특별시 영등포구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:선릉역', 'SUBWAY_STATION', '선릉역', '선릉역', '선릉역', '서울특별시 강남구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:삼성역', 'SUBWAY_STATION', '삼성역', '삼성역', '삼성역', '서울특별시 강남구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:강남역', 'SUBWAY_STATION', '강남역', '강남역', '강남역', '서울특별시 강남구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:교대역', 'SUBWAY_STATION', '교대역', '교대역', '교대역', '서울특별시 서초구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:잠실역', 'SUBWAY_STATION', '잠실역', '잠실역', '잠실역', '서울특별시 송파구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:사당역', 'SUBWAY_STATION', '사당역', '사당역', '사당역', '서울특별시 동작구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:고속터미널역', 'SUBWAY_STATION', '고속터미널역', '고속터미널역', '고속터미널역', '서울특별시 서초구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:건대입구역', 'SUBWAY_STATION', '건대입구역', '건대입구역', '건대입구역', '서울특별시 광진구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:왕십리역', 'SUBWAY_STATION', '왕십리역', '왕십리역', '왕십리역', '서울특별시 성동구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP),
('KOREA_SEED', 'subway:서울:노원역', 'SUBWAY_STATION', '노원역', '노원역', '노원역', '서울특별시 노원구', NULL, NULL, 300, TRUE, CURRENT_TIMESTAMP)
;